name: Java CI/CD Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  # Первый Job: Сборка проекта
  build:
    name: Сборка проекта
    runs-on: ubuntu-latest  # Используем Ubuntu как среду
    steps:
      - name: Checkout кода
        uses: actions/checkout@v3
      - name: Установка Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Компиляция проекта
        run: |
          javac -d out src/Lara/WeatherApp.java
          jar cfe weather-app.jar Lara.WeatherApp -C out .
      - name: Сохранение артефакта
        uses: actions/upload-artifact@v3
        with:
          name: weather-app
          path: weather-app.jar

  # Второй Job: Тестирование проекта
  test:
    name: Тестирование проекта
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout кода
        uses: actions/checkout@v3

      - name: Установка Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Скачивание артефакта
        uses: actions/download-artifact@v3
        with:
          name: weather-app
          path: .

      - name: Запуск тестов
        run: |
          java -jar weather-app.jar
          echo "Тестирование завершено"

  # Третий Job: Линтинг и анализ кода
  lint:
    name: Линтинг кода
    runs-on: ubuntu-latest
    steps:
      - name: Checkout кода
        uses: actions/checkout@v3

      - name: Установка Java JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Проверка стиля кода
        run: echo "Проверка стиля кода выполнена успешно"

  # Четвёртый Job: Деплой (пример)
  deploy:
    name: Деплой приложения
    runs-on: ubuntu-latest
    needs: [build, test, lint]

    steps:
      - name: Скачивание артефакта
        uses: actions/download-artifact@v3
        with:
          name: weather-app
          path: .

      - name: Деплой приложения (эмуляция)
        run: |
          echo "Загрузка файла weather-app.jar на сервер..."
          sleep 2
          echo "Приложение успешно задеплоено!"
