name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Запускать на коммитах в ветку master

jobs:
  build:
    runs-on: ubuntu-latest  # Используемая среда

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Установить JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Сборка проекта
        run: |
          javac WeatherApp.java
          jar cfe weather-app.jar WeatherApp WeatherApp.class

      - name: Проверка результата
        run: ls -l
